### ISSUE TITLE
Adding a license?

### ISSUE THREAD

**Issue by hr-oss** [MetantiConan/Parallel_Overhead_Game#1]
Howdy!

Love this game :D I was curious, if you’d like to add a license to the repo? I did see in the readme you put copyright there, but it’s always good to have a dedicated license file so people don’t get confused !

Here’s a tutorial on how to add a license: https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/adding-a-license-to-a-repository

Thank you !

**Comment by MetantiConan** [comment]
I thought about adding a license, but since I was busy with my other account, I didn't have much time, I am thinking of adding Mozilla Public License.

**Comment by hr-oss** [comment]
Hey great ! I see you added a license and contributing document, thanks! :D 

When I’ve got a moment, I’d love to contribute😊
